apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: monitor
spec:
  hard:
    pods: "100"
    requests.cpu: "1000m"
    requests.memory: 1000Mi
    limits.cpu: "2500m"
    limits.memory: 3500Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: monitor-limit-range
  namespace: monitor
spec:
  limits:
    - default:
        cpu: 100m
        memory: 64Mi
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      type: Container
